services:
  - type: web
    name: whatsapp-nlp-backend
    runtime: python
    rootDir: whatsapp-nlp-bot/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MODEL_PATH
        value: ./best_fraud_detection_model.pkl
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
